# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  timeout: 5000
  username: payroll_user
  password: payroll_password

development:
  <<: *default
  database: payroll_development

test:
  <<: *default
  database: payroll_test

production:
  <<: *default
  database: postgres
  username: payroll
  password: 